// types/sections.ts
export type SectionType =
  | "dashboard"
  | "courses"
  | "users"
  | "skills"
  | "reports"
  | "certificates"
  | "calendar"
  | "messages"
  | "workflow"
  | "help"
  | "notification"
  | "settings"
  |"userdetails"
  |"coursedetails"
  | "reports-landing"
  | "reports-courses"
  | "reports-users"
  | "reports-matrix"
  | "reports-timeline"
  | "Employee"
  | "groupspage"
  | "groupsmainpage"
  | "addgroupform"
  | "groupinfo"
  | "learning"
  

